// GENERATED by scripts/build-apps-script.mjs — do not edit here.
// Edit the files under src/ and run `npm run build:script`, then paste this
// whole file into the Apps Script editor (docs/setup.md, Tahap 6).

// ───── src/lib/tarifHistoris.js ─────
// Shared "what was true as of month X" lookup — the one place that walks
// RumahRiwayat/TarifVersi (docs/sheets-schema.md). Both are append-only: the
// latest row(s) whose periode <= target win — never edited, only added to.
//
// This file (with tagihan.js, rumah.js, ringkasan.js and server/core.js) also
// runs inside Google Apps Script — scripts/build-apps-script.mjs concatenates
// them into apps-script/Code.gs. So: no browser/Vue imports, no `?.`/`??`.
const periodeOf = (tahun, bulan) => Number(tahun) * 100 + Number(bulan);

/** RumahRiwayat row: [alamat, tahun_berlaku, bulan_berlaku, luas, tipe] */
function luasTipePada(rumahRiwayatRows, alamatRumah, tahun, bulan) {
  const target = periodeOf(tahun, bulan);
  let best = null;
  for (const r of rumahRiwayatRows) {
    if (r[0] !== alamatRumah) continue;
    const p = periodeOf(r[1], r[2]);
    if (p <= target && (!best || p > best.p)) best = { p, luas: Number(r[3]), tipe: r[4] };
  }
  return best ? { luas: best.luas, tipe: best.tipe } : null;
}

/** TarifVersi row: [tahun_berlaku, bulan_berlaku, komponen, luas_min, nominal].
 *  One rate card = every row sharing the latest (tahun, bulan) not after the
 *  target month, so the number of ISLK tiers is free:
 *  - `islk_rumah`   — luas_min (m²) + monthly ISLK; a house pays the row with
 *                     the largest luas_min <= its luas
 *  - `islk_kavling` — nominal per m²
 *  - `iuran_rt`     — flat, every house
 *  Returns null when no version is effective yet. */
function rateCardPada(tarifVersiRows, tahun, bulan) {
  const target = periodeOf(tahun, bulan);
  let versi = null;
  for (const r of tarifVersiRows) {
    const p = periodeOf(r[0], r[1]);
    if (p <= target && (versi == null || p > versi)) versi = p;
  }
  if (versi == null) return null;
  const rows = tarifVersiRows.filter((r) => periodeOf(r[0], r[1]) === versi);
  const nominal = (komponen) => {
    const r = rows.find((x) => x[2] === komponen);
    return r ? Number(r[4]) : null;
  };
  return {
    rumah: rows.filter((r) => r[2] === 'islk_rumah')
      .map((r) => [Number(r[3]) || 0, Number(r[4])]).sort((a, b) => a[0] - b[0]),
    kavlingPerM2: nominal('islk_kavling'),
    iuranRt: nominal('iuran_rt') == null ? 0 : nominal('iuran_rt'),
  };
}

/** ISLK for one house under one rate card — null if the card has no rule for
 *  its tipe/luas (an incomplete TarifVersi row set is never billed as Rp0). */
function islk({ luas, tipe }, rateCard) {
  if (tipe === 'kavling') return rateCard.kavlingPerM2 == null ? null : rateCard.kavlingPerM2 * luas;
  let tarif = null;
  for (const [luasMin, nominal] of rateCard.rumah) if (luas >= luasMin) tarif = nominal;
  return tarif;
}

/** Full tarif for one house, as of a given (tahun, bulan) — null if the house,
 *  the rate card, or the matching rule isn't there by then. */
function tarifPada(rumahRiwayatRows, tarifVersiRows, alamatRumah, tahun, bulan) {
  const lt = luasTipePada(rumahRiwayatRows, alamatRumah, tahun, bulan);
  const rc = lt && rateCardPada(tarifVersiRows, tahun, bulan);
  const i = rc && islk(lt, rc);
  return i == null ? null : i + rc.iuranRt;
}

// ───── src/lib/tagihan.js ─────
// The one place that turns "which months has this house paid" into status,
// tunggakan and aging — for every screen and every year. The Sheet only says
// which periodes are sah/pending per house ('D-API'!L/M, docs/sheets-schema.md
// `D-API`); everything that needs a tarif is resolved here with tarifPada(), the
// same lookup the rest of the app uses, so there's no second copy of the rate
// logic living in a Sheet formula.
//
// A month is always paid in full (no partial payments — docs/sheets-schema.md
// `D-Pembayaran`), so a month is simply Lunas, Pending, Belum, or '-' (not billed:
// before the house's first RumahRiwayat row, not due yet, or no rate card).

const tahunOf = (p) => Math.floor(p / 100);
const bulanOf = (p) => p % 100;

/** Periode `n` months after `p` (n may be negative). */
function geserPeriode(p, n) {
  const idx = tahunOf(p) * 12 + (bulanOf(p) - 1) + n;
  return Math.floor(idx / 12) * 100 + (idx % 12) + 1;
}

/** Whole months from `a` to `b` (b - a). */
const selisihBulan = (a, b) =>
  (tahunOf(b) - tahunOf(a)) * 12 + (bulanOf(b) - bulanOf(a));

/** "Sep" for the current year, "Sep '25" for any other. */
function labelBulan(p, tahunIni, BULAN) {
  const nama = BULAN[bulanOf(p) - 1].slice(0, 3);
  return tahunOf(p) === tahunIni ? nama : `${nama} '${String(tahunOf(p)).slice(2)}`;
}

/** Earliest RumahRiwayat periode for a house — billing starts here. */
function mulaiTagih(rumahRiwayatRows, alamat) {
  let min = null;
  for (const r of rumahRiwayatRows) {
    if (r[0] !== alamat) continue;
    const p = periodeOf(r[1], r[2]);
    if (min == null || p < min) min = p;
  }
  return min;
}

/**
 * Everything the app shows about one house's dues, as of `sekarang` (a periode).
 * `h` needs { alamat, lunas:Set<periode>, pending:Set<periode> }.
 */
function hitungTagihan(h, rumahRiwayatRows, tarifVersiRows, sekarang) {
  const tarifPer = (p) => tarifPada(rumahRiwayatRows, tarifVersiRows, h.alamat, tahunOf(p), bulanOf(p));
  const mulai = mulaiTagih(rumahRiwayatRows, h.alamat);

  function statusPada(p) {
    if (h.lunas.has(p)) return 'Lunas';
    if (h.pending.has(p)) return 'Pending';
    if (mulai == null || p < mulai || p > sekarang || tarifPer(p) == null) return '-';
    return 'Belum';
  }

  // Every due, unpaid, not-pending month since billing started, oldest first.
  // Pending transfers aren't owed any more from the resident's side — bendahara
  // clears them from the Kas screen.
  const tunggakanList = [];
  if (mulai != null) {
    for (let p = mulai; p <= sekarang; p = geserPeriode(p, 1)) {
      if (statusPada(p) === 'Belum') tunggakanList.push({ periode: p, tarif: tarifPer(p) });
    }
  }

  /** 12-month card for any year: status + that month's own tarif. */
  const kartuTahun = (tahun) => {
    const bulan = Array.from({ length: 12 }, (_, i) => periodeOf(tahun, i + 1));
    return { status: bulan.map(statusPada), tarifBulan: bulan.map(tarifPer) };
  };

  return {
    mulai,
    tarif: tarifPer(sekarang),
    tunggakanList,
    tunggakan: tunggakanList.reduce((sum, t) => sum + t.tarif, 0),
    tertua: tunggakanList.length ? tunggakanList[0].periode : null,
    statusPada,
    tarifPer,
    kartuTahun,
  };
}

// ───── src/lib/rumah.js ─────
// D-API's per-house block (docs/sheets-schema.md `D-API`, cols D..M) → one object
// per active house, with status/tunggakan/tarif resolved from RumahRiwayat and
// TarifVersi. Used by the browser (Warga/Pos/Kas screens) and by the Apps Script
// server (public aggregates), so both always agree. No `?.`/`??` — it also runs
// in Apps Script (see tarifHistoris.js).
const periodeSet = (v) => new Set(v ? String(v).split(',').map(Number).filter(Boolean) : []);

/** `hari` = { tahun, bulan } — "today", from the server. */
function bangunRumah(apiRows, rumahRiwayatRows, tarifVersiRows, hari) {
  const sekarang = hari.tahun * 100 + hari.bulan;
  return apiRows
    .filter((r) => r[3] && String(r[10]).toUpperCase() !== 'FALSE')
    .map((r) => {
      const h = {
        alamat: String(r[3]), nama: r[4], telp: r[5] != null ? String(r[5]) : '',
        cluster: r[6], blok: String(r[7] == null ? '' : r[7]), rumah: String(r[8] == null ? '' : r[8]),
        pin: r[9] != null ? String(r[9]) : '',
        lunas: periodeSet(r[11]),
        pending: periodeSet(r[12]),
      };
      const t = hitungTagihan(h, rumahRiwayatRows, tarifVersiRows, sekarang);
      const lt = luasTipePada(rumahRiwayatRows, h.alamat, hari.tahun, hari.bulan);
      return Object.assign({}, h, t, {
        luas: lt ? lt.luas : null, tipe: lt ? lt.tipe : null,
        // No RumahRiwayat baseline (or no rate card) → never billed as Rp0;
        // every screen shows "Tarif belum diatur" and blocks paying instead.
        tarifDiatur: t.tarif != null,
        status: t.kartuTahun(hari.tahun).status,
      });
    });
}

// ───── src/lib/ringkasan.js ─────
// Everything the public /sum page shows — cluster-wide aggregates only, computed
// on the server (Apps Script) so per-house rows never leave the private Sheet
// (PDP — see RingkasanPublik.vue). Pure functions; also bundled into
// apps-script/Code.gs, so no `?.`/`??` (see tarifHistoris.js).

// Aging buckets, counted only for houses already ≥ 3 months behind. Colours live
// in the view (index-matched); everything here is numbers.
const BUCKET = [
  { label: '3–6 bulan', min: 3, max: 6 },
  { label: '6–12 bulan', min: 6, max: 12 },
  { label: '1–3 tahun', min: 12, max: 36 },
  { label: '> 3 tahun', min: 36, max: Infinity },
];

const persen = (bagian, total) => (total ? Math.round((bagian / total) * 100) : 0);

/** Tabs are the raw tab rows (header row already dropped); `hari` = { tahun, bulan }. */
function ringkasanPublik(tabs, hari) {
  const houses = bangunRumah(tabs.api, tabs.rumahRiwayat, tabs.tarifVersi, hari);
  const sekarang = hari.tahun * 100 + hari.bulan;
  const meta = {};
  tabs.api.forEach((r) => { if (r[0]) meta[r[0]] = r[1]; });

  // Terkumpul per month from D-Riwayat (newest row first → oldest first), leading
  // all-zero months trimmed; each month's target = every house's tarif that month.
  const bulanan = tabs.riwayat
    .filter((r) => r[0] && r[1])
    .map((r) => ({ tahun: Number(r[0]), bulan: Number(r[1]), terkumpul: Number(r[2]) || 0 }))
    .reverse();
  const nolAwal = bulanan.findIndex((b) => b.terkumpul > 0);
  const riwayat = (nolAwal <= 0 ? bulanan : bulanan.slice(nolAwal)).map((b) => ({
    tahun: b.tahun, bulan: b.bulan, terkumpul: b.terkumpul,
    target: houses.reduce((sum, h) => sum + (tarifPada(tabs.rumahRiwayat, tabs.tarifVersi, h.alamat, b.tahun, b.bulan) || 0), 0),
  }));
  const iniBulan = riwayat.find((b) => b.tahun === hari.tahun && b.bulan === hari.bulan);

  // Opex — category totals only.
  const opexList = tabs.opex.filter((r) => r[0]).map((r) => ({
    kategori: r[0], ikon: r[1] || '📋', nominal: Number(r[2]) || 0, diperbarui: r[3] ? String(r[3]) : '',
  }));
  const tglOpex = opexList.map((o) => o.diperbarui).filter(Boolean).sort();

  // Paid ahead: every sah month not yet due, at the tarif in force that month.
  const muka = { rumah: 0, bulanTahunIni: 0, nominalTahunIni: 0, bulanTahunDepan: 0, nominalTahunDepan: 0 };
  houses.forEach((h) => {
    const depan = Array.from(h.lunas).filter((p) => p > sekarang);
    if (depan.length) muka.rumah += 1;
    depan.forEach((p) => {
      const nominal = h.tarifPer(p) || 0;
      if (tahunOf(p) === hari.tahun) { muka.bulanTahunIni += 1; muka.nominalTahunIni += nominal; }
      else { muka.bulanTahunDepan += 1; muka.nominalTahunDepan += nominal; }
    });
  });
  muka.total = muka.nominalTahunIni + muka.nominalTahunDepan;

  // Aging: age runs from the oldest unpaid month (across years) to this month.
  const nunggak = houses.filter((h) => h.tertua).map((h) => ({
    umur: selisihBulan(h.tertua, sekarang) + 1, nominal: h.tunggakan,
  }));
  const aging = nunggak.filter((h) => h.umur >= 3);
  const nominalAging = aging.reduce((sum, h) => sum + h.nominal, 0);

  return {
    jumlahRumah: houses.length,
    tunggakan: houses.reduce((sum, h) => sum + h.tunggakan, 0),
    target: houses.reduce((sum, h) => sum + (h.tarif || 0), 0),
    lunasBulanIni: houses.filter((h) => h.lunas.has(sekarang)).length,
    terkumpulBulanIni: iniBulan ? iniBulan.terkumpul : 0,
    kas: Number(meta.kas_tunai || 0),
    rekening: Number(meta.rekening || 0),
    opex: opexList.reduce((sum, o) => sum + o.nominal, 0),
    opexDiperbarui: tglOpex.length ? tglOpex[tglOpex.length - 1] : '',
    opexList,
    riwayat,
    dibayarDimuka: muka,
    aging: {
      jumlahRumah: nunggak.length,
      belumDianggap: nunggak.length - aging.length,
      jumlahAging: aging.length,
      nominalAging,
      distribusi: BUCKET.map((b) => {
        const di = aging.filter((h) => h.umur >= b.min && h.umur < b.max);
        const nominal = di.reduce((sum, h) => sum + h.nominal, 0);
        return {
          label: b.label, jumlah: di.length, nominal,
          persenRumah: persen(di.length, aging.length), persenNominal: persen(nominal, nominalAging),
        };
      }),
    },
  };
}

/** One dues year's summary (sah rows only) from a D-Iuran<tahun> tab's rows
 *  (`D-Pembayaran` column order): per-month totals + per-metode totals. */
function ringkasTahun(rows) {
  const sah = rows.filter((r) => r[1] && String(r[1]).charAt(0) !== '#' && r[8] === 'sah');
  const perMetode = {};
  sah.forEach((r) => { perMetode[r[5]] = (perMetode[r[5]] || 0) + (Number(r[4]) || 0); });
  return {
    bulan: Array.from({ length: 12 }, (_, i) => {
      const di = sah.filter((r) => Number(r[2]) === i + 1);
      const rumah = {};
      di.forEach((r) => { rumah[r[1]] = true; });
      return { bulan: i + 1, total: di.reduce((sum, r) => sum + (Number(r[4]) || 0), 0),
               rumah: Object.keys(rumah).length };
    }),
    perMetode,
    total: sah.reduce((sum, r) => sum + (Number(r[4]) || 0), 0),
  };
}

// ───── src/server/core.js ─────
// The read gateway between the app and the private Sheet. One pure function,
// `handle(req, ctx)`, run by Google Apps Script in production (bundled into
// apps-script/Code.gs, with src/server/gas.js as the thin doPost wrapper) and by
// the browser's local mock mode (src/lib/apiLokal.js) — so what the tests see is
// what runs for real. Also bundled, so no `?.`/`??` (see lib/tarifHistoris.js).
//
// ctx = {
//   tab(name)            → rows of a tab, header row dropped, '' → null
//   prop(name)           → a Script Property (POS_PIN, KAS_PIN)
//   cache                → { get(key), put(key, value, ttlSeconds), remove(key) }
//   hari()               → { tahun, bulan } — "today" in the Sheet's time zone
// }
//
// Who gets what (the point of the whole thing — the Sheet itself is private):
//   publik  nobody's PIN   aggregates only, no house rows (PDP)
//   warga   alamat + PIN   that one house's rows + its own RumahRiwayat
//   pos     POS_PIN        every active house, without phone numbers or PINs
//   kas     KAS_PIN        + phone numbers, balances, pending/cash ledgers
// Rows are returned raw (the app's own lib/tagihan.js turns them into status).

const GAGAL_MAKS_WARGA = 5;      // wrong PINs per house before it locks…
const GAGAL_MAKS_PETUGAS = 10;   // …and per petugas role (a global counter)
const KUNCI_DETIK = 900;         // …for 15 minutes
const PUBLIK_DETIK = 60;         // public aggregates are cached this long

const gagal = (kode, pesan) => ({ ok: false, kode, pesan: pesan || '' });

// ── PIN checks, with a lock-out so 3 digits can't simply be brute-forced ───
// (cache keys are capped at 250 chars; a made-up giant alamat must not throw)
const kunciGagal = (kunci) => 'gagal:' + String(kunci).slice(0, 60);
function terkunci(ctx, kunci, maks) {
  return Number(ctx.cache.get(kunciGagal(kunci)) || 0) >= maks;
}
function catatGagal(ctx, kunci) {
  ctx.cache.put(kunciGagal(kunci), String(Number(ctx.cache.get(kunciGagal(kunci)) || 0) + 1), KUNCI_DETIK);
}
function bersihkanGagal(ctx, kunci) {
  ctx.cache.remove(kunciGagal(kunci));
}

/** → null when OK, else the failure response. */
function cekPetugas(ctx, role, pin) {
  if (role !== 'pos' && role !== 'kas') return gagal('role');
  const benar = ctx.prop(role === 'pos' ? 'POS_PIN' : 'KAS_PIN');
  if (!benar) return gagal('config', 'PIN belum diatur di Script Properties (POS_PIN / KAS_PIN).');
  if (terkunci(ctx, role, GAGAL_MAKS_PETUGAS)) return gagal('terkunci');
  if (String(pin == null ? '' : pin) !== String(benar)) {
    catatGagal(ctx, role);
    return gagal('pin');
  }
  bersihkanGagal(ctx, role);
  return null;
}

/** Unknown house, deactivated house and wrong PIN all answer the same 'pin', so
 *  addresses can't be enumerated. → { gagal } or { baris }. */
function cekWarga(ctx, alamat, pin) {
  const id = String(alamat == null ? '' : alamat);
  if (terkunci(ctx, id, GAGAL_MAKS_WARGA)) return { gagal: gagal('terkunci') };
  const baris = ctx.tab('D-API').find((r) =>
    r[3] && String(r[3]) === id && String(r[10]).toUpperCase() !== 'FALSE');
  const benar = baris && baris[9] != null ? String(baris[9]) : '';
  if (!benar || String(pin == null ? '' : pin) !== benar) {
    catatGagal(ctx, id);
    return { gagal: gagal('pin') };
  }
  bersihkanGagal(ctx, id);
  return { baris };
}

// ── Shaping rows per role ──────────────────────────────────────────────────
// D-API row: 0 key · 1 value · 3 alamat · 4 nama · 5 telp · 9 pin · 10 aktif …
const aktif = (r) => r[3] && String(r[10]).toUpperCase() !== 'FALSE';

function sanitasi(r, opsi) {
  const c = r.slice();
  if (!aktif(r)) for (let i = 2; i < c.length; i += 1) c[i] = null;   // a deactivated house sends nothing
  c[9] = null;                       // nobody gets a PIN back
  if (!opsi.telp) c[5] = null;
  if (!opsi.meta) { c[0] = null; c[1] = null; }
  return c;
}

/** D-API rows for a role: active houses (plus the key/value balance rows for Kas). */
function barisApi(ctx, opsi) {
  return ctx.tab('D-API')
    .filter((r) => aktif(r) || (opsi.meta && r[0]))
    .map((r) => sanitasi(r, opsi));
}

const dasar = (ctx, hari) => ({
  ok: true,
  hari: { tahun: hari.tahun, bulan: hari.bulan },
  tarifVersi: ctx.tab('M-TarifVersi'),
  blok: ctx.tab('M-Blok'),
});

function publik(ctx, hari) {
  const hit = ctx.cache.get('publik');
  if (hit) return JSON.parse(hit);
  const hasil = Object.assign({ ok: true, hari: { tahun: hari.tahun, bulan: hari.bulan } },
    ringkasanPublik({
      api: ctx.tab('D-API'), rumahRiwayat: ctx.tab('M-RumahRiwayat'), tarifVersi: ctx.tab('M-TarifVersi'),
      opex: ctx.tab('M-Opex'), riwayat: ctx.tab('D-Riwayat'),
    }, hari));
  ctx.cache.put('publik', JSON.stringify(hasil), PUBLIK_DETIK);
  return hasil;
}

function warga(ctx, hari, req) {
  const cek = cekWarga(ctx, req.alamat, req.pin);
  if (cek.gagal) return cek.gagal;
  const id = String(cek.baris[3]);
  const p = dasar(ctx, hari);
  p.api = [sanitasi(cek.baris, {})];   // this house only
  p.rumahRiwayat = ctx.tab('M-RumahRiwayat').filter((r) => String(r[0]) === id);
  return p;
}

function pos(ctx, hari, req) {
  const g = cekPetugas(ctx, 'pos', req.pin);
  if (g) return g;
  const p = dasar(ctx, hari);
  p.api = barisApi(ctx, {});
  p.rumahRiwayat = ctx.tab('M-RumahRiwayat');
  p.petugas = ctx.tab('M-Petugas').filter((r) => r[1] === 'satpam');
  return p;
}

function kas(ctx, hari, req) {
  const g = cekPetugas(ctx, 'kas', req.pin);
  if (g) return g;
  const p = dasar(ctx, hari);
  p.api = barisApi(ctx, { meta: true, telp: true });
  p.rumahRiwayat = ctx.tab('M-RumahRiwayat');
  p.petugas = ctx.tab('M-Petugas').filter((r) => r[1] === 'bendahara');
  p.pending = ctx.tab('D-Pending');
  p.kasMasuk = ctx.tab('D-KasMasuk');
  return p;
}

function kasTahun(ctx, hari, req) {
  const g = cekPetugas(ctx, 'kas', req.pin);
  if (g) return g;
  const tahun = Math.floor(Number(req.tahun));
  if (!(tahun >= 2000 && tahun <= 2100)) return gagal('tahun');
  let rows;
  try { rows = ctx.tab('D-Iuran' + tahun); } catch (e) { return gagal('tab', 'Tab D-Iuran' + tahun + ' belum ada.'); }
  return { ok: true, hari: { tahun: hari.tahun, bulan: hari.bulan }, tahun, ringkasan: ringkasTahun(rows) };
}

function handle(req, ctx) {
  try {
    const hari = ctx.hari();
    switch (req && req.action) {
      case 'publik': return publik(ctx, hari);
      case 'login': {
        const g = cekPetugas(ctx, req.role, req.pin);
        return g || { ok: true };
      }
      case 'warga': return warga(ctx, hari, req);
      case 'pos': return pos(ctx, hari, req);
      case 'kas': return kas(ctx, hari, req);
      case 'kasTahun': return kasTahun(ctx, hari, req);
      default: return gagal('action');
    }
  } catch (e) {
    return gagal('server', String(e && e.message ? e.message : e));
  }
}

// ───── src/server/gas.js ─────
/* eslint-disable no-undef */
// Google Apps Script wrapper — the only part of the server that touches Google
// services. Appended after the bundled src/lib + src/server/core.js code by
// scripts/build-apps-script.mjs; never imported by the app itself.
//
// Deploy: Extensions → Apps Script in the Iuran_ClusterN spreadsheet, paste
// apps-script/Code.gs, set Script Properties POS_PIN / KAS_PIN, then
// Deploy → New deployment → Web app (Execute as: Me, Who has access: Anyone).
// docs/setup.md, Tahap 6.

function bacaTab(nama) {
  var ss = SpreadsheetApp.getActiveSpreadsheet();
  var sheet = ss.getSheetByName(nama);
  if (!sheet) throw new Error('Tab tidak ditemukan: ' + nama);
  var tz = ss.getSpreadsheetTimeZone();
  var rows = sheet.getDataRange().getValues().slice(1).map(function (r) {
    return r.map(function (c) {
      if (c === '') return null;
      if (c instanceof Date) {
        var jam = Utilities.formatDate(c, tz, 'HH:mm:ss');
        return Utilities.formatDate(c, tz, jam === '00:00:00' ? 'yyyy-MM-dd' : 'yyyy-MM-dd HH:mm:ss');
      }
      return c;
    });
  });
  while (rows.length && rows[rows.length - 1].every(function (c) { return c === null; })) rows.pop();
  return rows;
}

function buatKonteks() {
  var cache = CacheService.getScriptCache();
  var props = PropertiesService.getScriptProperties();
  return {
    tab: bacaTab,
    prop: function (k) { return props.getProperty(k); },
    cache: {
      get: function (k) { return cache.get(k); },
      put: function (k, v, detik) { cache.put(k, v, detik); },
      remove: function (k) { cache.remove(k); },
    },
    hari: function () {
      var tz = SpreadsheetApp.getActiveSpreadsheet().getSpreadsheetTimeZone();
      var p = Utilities.formatDate(new Date(), tz, 'yyyy-M').split('-');
      return { tahun: Number(p[0]), bulan: Number(p[1]) };
    },
  };
}

function jawab(obj) {
  return ContentService.createTextOutput(JSON.stringify(obj)).setMimeType(ContentService.MimeType.JSON);
}

// The app POSTs JSON as text/plain — a "simple" request, so the browser skips
// the CORS preflight that Apps Script web apps can't answer.
function doPost(e) {
  var req;
  try { req = JSON.parse(e.postData.contents); } catch (err) { return jawab({ ok: false, kode: 'request' }); }
  return jawab(handle(req, buatKonteks()));
}

// Open the /exec URL in a browser to check the deployment is live.
function doGet() {
  return jawab({ ok: true, pesan: 'Iuran API aktif' });
}
